#!/usr/bin/env node

/**
 * This script creates a runtime config file from Vercel environment variables
 * Run this BEFORE the Vite build to ensure env vars are available
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log('🔧 Injecting environment variables...');

const envVars = {
  VITE_SUPABASE_URL: process.env.VITE_SUPABASE_URL,
  VITE_SUPABASE_ANON_KEY: process.env.VITE_SUPABASE_ANON_KEY,
  VITE_UNSPLASH_ACCESS_KEY: process.env.VITE_UNSPLASH_ACCESS_KEY,
};

// Check which variables are set
Object.entries(envVars).forEach(([key, value]) => {
  if (value) {
    console.log(`✅ ${key}: SET`);
  } else {
    console.log(`❌ ${key}: MISSING`);
  }
});

// Create a JavaScript config file that can be imported
const configContent = `// Auto-generated by inject-env.js - DO NOT EDIT
// This file contains environment variables from Vercel
export const config = {
  VITE_SUPABASE_URL: ${JSON.stringify(envVars.VITE_SUPABASE_URL || '')},
  VITE_SUPABASE_ANON_KEY: ${JSON.stringify(envVars.VITE_SUPABASE_ANON_KEY || '')},
  VITE_UNSPLASH_ACCESS_KEY: ${JSON.stringify(envVars.VITE_UNSPLASH_ACCESS_KEY || '')},
};
`;

const configPath = path.join(__dirname, '..', 'src', 'runtime-config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log(`✅ Created ${configPath}`);
console.log('📦 Environment variables injected successfully!');
